-- Create a new database called 'COOHOMELESS_DB'
-- Connect to the 'master' database to run this snippet
CREATE DATABASE IF NOT EXISTS COOHOMELESS_DB;
USE COOHOMELESS_DB;

-- SCRIPTS TABLE: USER
-- TABLE 'USER'
-- CREATE TABLE `USER` (
--     ID_USER INTEGER NOT NULL AUTO_INCREMENT,
--     FULL_NAME VARCHAR(100) NOT NULL,
--     URL_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_profile_pic',
--     USER_TYPE INT,
-- 	   CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
--     PRIMARY KEY(ID_USER)
-- );

-- SCRIPTS TABLE: ORGANIZATION
-- TABLE 'ORGANIZATION'
CREATE TABLE `organization` (
    ID_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    DESC_ORGANIZATION VARCHAR(100),
    CNPJ VARCHAR(14),
	URI_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_ong_pic',
	PRIMARY KEY(ID_ORGANIZATION)
);

-- SCRIPTS TABLE: CONTRIBUTOR
-- TABLE 'CONTRIBUTOR'
CREATE TABLE `contributor` (
    ID_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    CPF VARCHAR(11),
	URI_PROFILE_IMAGE VARCHAR(255) DEFAULT '/path/to/default_contributor_pic',
	PRIMARY KEY(ID_CONTRIBUTOR)
);

-- SCRIPTS TABLE: HOMELESS
-- TABLE 'HOMELESS'
CREATE TABLE `homeless` (
    ID_HOMELESS INTEGER AUTO_INCREMENT NOT NULL,
	`NAME` VARCHAR(50),
	PHOTO VARCHAR(200),
    BACKGROUND VARCHAR(250),
    STATUS_TYPE ENUM('FOME', 'SAÚDE', 'FRIO'),
	`ANONYMOUS` CHAR(1) NOT NULL DEFAULT 'Y',
	ID_HOMELESS_INFO INTEGER NOT NULL,
	ID_HOMELESS_STATUS INTEGER NOT NULL,
    PRIMARY KEY(ID_HOMELESS),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_HOMELESS_HOMELESS_DATAIL FOREIGN KEY(ID_HOMELESS_INFO) REFERENCES HOMELESS_INFO(ID_HOMELESS_INFO),
	CONSTRAINT CHK_HOMELESS CHECK (`ANONYMOUS` = 'Y' OR `ANONYMOUS` = 'N')
);

-- TABLE 'HOMELESS_INFO'
CREATE TABLE `homeless_info` (
    ID_HOMELESS_INFO INTEGER AUTO_INCREMENT NOT NULL,
	GENDER VARCHAR(20),
	BIRTH_DATE DATETIME,
	HAIR_COLOR VARCHAR(20),
	HAIR_TYPE VARCHAR(20),
	ETNIA VARCHAR(20),
	EYES VARCHAR(20),
	PHYSICAL_TYPE VARCHAR(20),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_HOMELESS_INFO)
);

-- SCRIPTS TABLE: MEETING_POINT_CONTRIBUTOR
-- TABLE 'MEETING_POINT_CONTRIBUTOR'
CREATE TABLE `meeting_point_contributor` (
    ID_MEETING_POINT_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT,
    ID_HOMELESS INTEGER NOT NULL,
    ID_CONTRIBUTOR INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_MEETING_POINT_CONTRIBUTOR),
    CONSTRAINT FK_MEETING_POINT_CONTRIBUTOR_HOMELESS FOREIGN KEY(ID_HOMELESS) REFERENCES HOMELESS(ID_HOMELESS),
    CONSTRAINT FK_MEETING_POINT_CONTRIBUTOR_CONTRIBUTOR FOREIGN KEY(ID_CONTRIBUTOR) REFERENCES `CONTRIBUTOR`(ID_CONTRIBUTOR)
);

-- SCRIPTS TABLE: MEETING_POINT_ORGANIZATION
-- TABLE 'MEETING_POINT_ORGANIZATION'
CREATE TABLE `meeting_point_organization` (
    ID_MEETING_POINT_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT,
    ID_HOMELESS INTEGER NOT NULL,
    ID_ORGANIZATION INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_MEETING_POINT_ORGANIZATION),
    CONSTRAINT FK_MEETING_POINT_ORGANIZATION_HOMELESS FOREIGN KEY(ID_HOMELESS) REFERENCES HOMELESS(ID_HOMELESS),
    CONSTRAINT FK_MEETING_POINT_ORGANIZATION_ORGANIZATION FOREIGN KEY(ID_ORGANIZATION) REFERENCES `ORGANIZATION`(ID_ORGANIZATION)
);

-- SCRIPTS TABLE: LOCATION_CONTRIBUTOR
-- TABLE 'LOCATION_CONTRIBUTOR'
CREATE TABLE `location_contributor` (
    ID_LOCATION_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT,
    CITY VARCHAR(20),
	UF VARCHAR(20),
	DESC_LOCATION_CONTRIBUTOR VARCHAR(200),
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
	ID_MEETING_POINT_CONTRIBUTOR INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_LOCATION_CONTRIBUTOR),
	CONSTRAINT FK_LOCATION_CONTRIBUTOR_MEETING_POINT FOREIGN KEY(ID_MEETING_POINT_CONTRIBUTOR) REFERENCES MEETING_POINT_CONTRIBUTOR(ID_MEETING_POINT_CONTRIBUTOR)
);
-- INDEX FOR 'ID_MEETING' IN 'LOCATION_CONTRIBUTOR'
CREATE INDEX IDX_LOCATION_CONTRIBUTOR_MEETING ON LOCATION_CONTRIBUTOR (ID_MEETING_POINT_CONTRIBUTOR);

-- SCRIPTS TABLE: LOCATION_ONG
-- TABLE 'LOCATION_ONG'
CREATE TABLE `location_ong` (
    ID_LOCATION_ONG INTEGER NOT NULL AUTO_INCREMENT,
    CITY VARCHAR(20),
	UF VARCHAR(20),
	DESC_LOCATION_ONG VARCHAR(200),
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
	ID_MEETING_POINT_ORGANIZATION INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_LOCATION_ONG),
	CONSTRAINT FK_LOCATION_ONG_MEETING_POINT FOREIGN KEY(ID_MEETING_POINT_ORGANIZATION) REFERENCES MEETING_POINT_ORGANIZATION(ID_MEETING_POINT_ORGANIZATION)
);
-- INDEX FOR 'ID_MEETING' IN 'LOCATION_ONG'
CREATE INDEX IDX_LOCATION_ONG_MEETING ON LOCATION_ONG (ID_MEETING_POINT_ORGANIZATION);

-- SCRIPTS TABLE: DONATION
-- TABLE 'DONATION'
CREATE TABLE `donation` (
    ID_DONATION INTEGER AUTO_INCREMENT NOT NULL,
    ID_DONATION_STATUS INTEGER NOT NULL,
    ID_DONATION_ITEM INTEGER NOT NULL,
    PRIMARY KEY(ID_DONATION),
    CONSTRAINT FK_DONATION_DONATION_STATUS FOREIGN KEY(ID_DONATION) REFERENCES DONATION_STATUS(ID_DONATION_STATUS),
    CONSTRAINT FK_DONATION_DONATION_ITEM FOREIGN KEY(ID_DONATION) REFERENCES DONATION_ITEM(ID_DONATION_ITEM)
);

-- TABLE 'DONATION_STATUS'
CREATE TABLE `donation_status` (
    ID_DONATION_STATUS INTEGER AUTO_INCREMENT NOT NULL,
	`TYPE` ENUM('FAIL', 'DOING', 'DONE'),
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_DONATION_STATUS)
);

-- TABLE 'DONATION_ITEM'
CREATE TABLE `donation_item` (
    ID_DONATION_ITEM INTEGER AUTO_INCREMENT NOT NULL,
    `TYPE` ENUM('VESTIMENTA', 'ALIMENTO', 'SAÚDE', 'HIGIENE', 'ANIMAL'),
    PRIMARY KEY(ID_DONATION_STATUS)
);

