-- SCRIPTS TABLE: HOMELESS

-- TABLE 'HOMELESS'
CREATE TABLE `HOMELESS` (
    ID_HOMELESS INTEGER AUTO_INCREMENT NOT NULL,
	`NAME` VARCHAR(50),
	PHOTO VARCHAR(200),
    BACKGROUND VARCHAR(250),
    STATUS_TYPE ENUM('FOME', 'SAÚDE', 'FRIO'),
	`ANONYMOUS` CHAR(1) NOT NULL DEFAULT 'N',
	ID_HOMELESS_INFO INTEGER NOT NULL,
	ID_HOMELESS_STATUS INTEGER NOT NULL,
    PRIMARY KEY(ID_HOMELESS),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT FK_HOMELESS_HOMELESS_DATAIL FOREIGN KEY(ID_HOMELESS_INFO) REFERENCES HOMELESS_INFO(ID_HOMELESS_INFO)
	CONSTRAINT CHK_HOMELESS CHECK (`ANONYMOUS` == 'Y' OR `ANONYMOUS` == 'N')
);

-- TABLE 'HOMELESS_INFO'
CREATE TABLE `HOMELESS_INFO` (
    ID_HOMELESS_INFO INTEGER AUTO_INCREMENT NOT NULL,
	GENDER VARCHAR(20),
	BIRTH_DATE DATETIME,
	HAIR_COLOR VARCHAR(20),
	HAIR_TYPE VARCHAR(20),
	ETNIA VARCHAR(20),
	EYES VARCHAR(20),
	PHYSICAL_TYPE VARCHAR(20),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_HOMELESS_INFO)
);

