-- SCRIPTS TABLE: USER

-- TABLE 'USER'
CREATE TABLE `USER` (
    ID_USER INTEGER NOT NULL AUTO_INCREMENT,
    FULL_NAME VARCHAR(100) NOT NULL,
    `PASSWORD` VARCHAR(50) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
    URL_PROFILE_IMAGE VARCHAR(255),
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(ID_USER)
);
