-- SCRIPTS TABLE: CONTRIBUTOR

-- TABLE 'CONTRIBUTOR'
CREATE TABLE CONTRIBUTOR (
    ID_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `NAME` VARCHAR(100),
    CPF VARCHAR(11),
	PRIMARY KEY(ID_CONTRIBUTOR)
);

-- TABLE 'MEETING_CONTRIBUTOR'
CREATE TABLE MEETING_CONTRIBUTOR (
    ID_MEETING_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRIMARY KEY(ID_MEETING_CONTRIBUTOR)
);