-- SCRIPTS TABLE: LOCALIZATION

-- TABLE 'LOCALIZATION'
CREATE TABLE LOCALIZATION (
    ID_LOCALIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY VARCHAR(20),
	UF VARCHAR(20),
	DESC_LOCALIZATION VARCHAR(200),
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
	ID_MEETING INTEGER NOT NULL,
	PRIMARY KEY(ID_LOCALIZATION),
	CONSTRAINT FK_LOCALIZATION_MEETING FOREIGN KEY(ID_MEETING) REFERENCES MEETING(ID_MEETING)
);
