-- SCRIPTS TABLE: MEETING

-- TABLE 'MEETING'
CREATE TABLE MEETING (
    ID_MEETING INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HOMELESS INTEGER NOT NULL,
	ID_MEETING_ORGANIZATION INTEGER NOT NULL,
	ID_MEETING_CONTRIBUTOR INTEGER NOT NULL,
	PRIMARY KEY(ID_MEETING)
);