-- Create a new database called 'CooHomelessDB'
USE CooHomelessDB;
CREATE DATABASE CooHomelessDB;

-- TABLE 'ORGANIZATION'
CREATE TABLE ORGANIZATION (
    ID_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME VARCHAR(50),
    DESC_ORGANIZATION VARCHAR(100),
    CNPJ VARCHAR(14),
	PRIMARY KEY(ID_ORGANIZATION)
);

-- TABLE 'CONTRIBUTOR'
CREATE TABLE CONTRIBUTOR (
    ID_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESC_CONTRIBUTOR VARCHAR(100),
    CPF VARCHAR(11),
	PRIMARY KEY(ID_CONTRIBUTOR)
);

-- TABLE 'MEETING_CONTRIBUTOR'
CREATE TABLE MEETING_CONTRIBUTOR (
    ID_MEETING_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRIMARY KEY(ID_MEETING_CONTRIBUTOR)
);

-- TABLE 'MEETING_ORGANIZATION'
CREATE TABLE MEETING_ORGANIZATION (
    ID_MEETING_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
	PRIMARY KEY(ID_MEETING_CONTRIBUTOR)
);

-- TABLE 'MEETING'
CREATE TABLE MEETING (
    ID_MEETING INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HOMELESS INTEGER NOT NULL,
	ID_MEETING_ORGANIZATION INTEGER NOT NULL,
	ID_MEETING_CONTRIBUTOR INTEGER NOT NULL,
	PRIMARY KEY(ID_MEETING)
);

-- TABLE 'LOCALIZATION'
CREATE TABLE LOCALIZATION (
    ID_LOCALIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CITY VARCHAR(20),
	UF VARCHAR(20),
	DESC_LOCALIZATION VARCHAR(200),
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
	ID_MEETING INTEGER NOT NULL,
	PRIMARY KEY(ID_LOCALIZATION),
	FOREIGN KEY(ID_MEETING) REFERENCES TO MEETING (ID_MEETING)
);

-- TABLE 'HOMELESS'
CREATE TABLE HOMELESS (
    ID_HOMELESS INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	"NAME" VARCHAR(50),
	PHOTO VARCHAR(200),
	ID_HOMELESS_DETAIL INTEGER NOT NULL,
	ID_HOMELESS_STATUS INTEGER NOT NULL,
	PRIMARY KEY(ID_HOMELESS),
	FOREIGN KEY(ID_HOMELESS_DETAIL) REFERENCES TO HOMELESS_DETAIL (ID_HOMELESS_DETAIL),
	FOREIGN KEY(ID_HOMELESS_STATUS) REFERENCES TO HOMELESS_STATUS (ID_HOMELESS_STATUS)
);

-- TABLE 'HOMELESS_STATUS'
CREATE TABLE HOMELESS_STATUS (
    ID_HOMELESS_STATUS INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	TIPO VARCHAR(20),
	PRIMARY KEY(ID_HOMELESS_STATUS)
);

-- TABLE 'HOMELESS_DETAIL'
CREATE TABLE HOMELESS_DETAIL (
    ID_HOMELESS_DETAIL INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	GENERO VARCHAR(20),
	DATA_NASCIMENTO DATETIME,
	CABELO_COR VARCHAR(20),
	CABELO_TIPO VARCHAR(20),
	ETNIA VARCHAR(20),
	OLHOS VARCHAR(20),
	TIPO_FISICO VARCHAR(20)
);


-- TABLE 'DONATION'
CREATE TABLE DONATION (
    ID_DONATION INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY
);



