-- Create a new database called 'CooHomelessDB'
USE CooHomelessDB;
CREATE DATABASE CooHomelessDB;

-- Create a new table called 'ORGANIZATION'
CREATE TABLE ORGANIZATION (
    ID_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    NOME NVARCHAR(50) NOT NULL,
    DESC_ORGANIZATION NVARCHAR(100),
    CNPJ INTEGER NOT NULL
);

-- Create a new table called 'COLLABORATOR'
CREATE TABLE COLLABORATOR (
    ID_COLLABORATOR INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    DESC_COLLABORATOR NVARCHAR(50) NOT NULL,
    CPF INTEGER NOT NULL
);


-- Create a new table called 'LOCALIZATION'
CREATE TABLE LOCALIZATION (
    ID_LOCALIZATION INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    ID_HOMELESS INTEGER NOT NULL,
    LATITUDE NVARCHAR(50) NOT NULL,
    LONGETUDE NVARCHAR(50) NOT NULL
);

CREATE TABLE homeless (
    id_homeless INTEGER AUTO_INCREMENT NOT NULL
);
 
CREATE TABLE donation (
    id_donation INTEGER AUTO_INCREMENT NOT NULL
);

CREATE TABLE city (
    id_city INTEGER AUTO_INCREMENT NOT NULL
);
