-- SCRIPTS TABLE: CONTRIBUTOR

-- TABLE 'CONTRIBUTOR'
CREATE TABLE CONTRIBUTOR (
    ID_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    CPF VARCHAR(11),
	PRIMARY KEY(ID_CONTRIBUTOR)
);

