-- SCRIPTS TABLE: CONTRIBUTOR

-- TABLE 'CONTRIBUTOR'
CREATE TABLE `CONTRIBUTOR` (
    ID_CONTRIBUTOR INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    CPF VARCHAR(11),
    ID_USER INTEGER NOT NULL,
	PRIMARY KEY(ID_CONTRIBUTOR),
    CONSTRAINT FK_CONTRIBUTOR_USER FOREIGN KEY(ID_USER) REFERENCES `USER`(ID_USER)
);

