-- SCRIPTS TABLE: DONATION

-- TABLE 'DONATION'
CREATE TABLE DONATION (
    ID_DONATION INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
    ID_DONATION_STATUS INTEGER NOT NULL,
    
    PRIMARY KEY(ID_DONATION)
);

-- TABLE 'DONATION_STATUS'
CREATE TABLE DONATION_STATUS (
    ID_DONATION_STATUS INTEGER AUTO_INCREMENT NOT NULL PRIMARY KEY,
	`TYPE` ENUM('FAIL', 'IN PROGRESS', 'DONE'),
    PRIMARY KEY(ID_DONATION_STATUS)
);
