-- SCRIPTS TABLE: HOMELESS

-- TABLE 'HOMELESS'
CREATE TABLE HOMELESS (
    ID_HOMELESS INTEGER AUTO_INCREMENT NOT NULL,
	`NAME` VARCHAR(50),
	PHOTO VARCHAR(200),
    DESC_HOMELESS VARCHAR(250),
    STATUS_TYPE ENUM('FOME', 'SAÚDE', 'FRIO'),
	ID_HOMELESS_DETAIL INTEGER NOT NULL,
	ID_HOMELESS_STATUS INTEGER NOT NULL,
    PRIMARY KEY(ID_HOMELESS),
	CONSTRAINT FK_HOMELESS_HOMELESS_DATAIL FOREIGN KEY(ID_HOMELESS_DETAIL) REFERENCES HOMELESS_DETAIL(ID_HOMELESS_DETAIL)
);

-- TABLE 'HOMELESS_DETAIL'
CREATE TABLE HOMELESS_DETAIL (
    ID_HOMELESS_DETAIL INTEGER AUTO_INCREMENT NOT NULL,
	GENDER VARCHAR(20),
	BIRTH_DATE DATETIME,
	HAIR_COLOR VARCHAR(20),
	HAIR_TYPE VARCHAR(20),
	ETNIA VARCHAR(20),
	EYES VARCHAR(20),
	PHYSICAL_TYPE VARCHAR(20),
    PRIMARY KEY(ID_HOMELESS_DETAIL)
);

