-- SCRIPTS TABLE: LOCALIZATION

-- TABLE 'LOCALIZATION'
CREATE TABLE `LOCALIZATION` (
    ID_LOCALIZATION INTEGER NOT NULL AUTO_INCREMENT,
    CITY VARCHAR(20),
	UF VARCHAR(20),
	DESC_LOCALIZATION VARCHAR(200),
    LATITUDE DECIMAL NOT NULL,
    LONGITUDE DECIMAL NOT NULL,
	ID_MEETING_POINT INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_LOCALIZATION),
	CONSTRAINT FK_LOCALIZATION_MEETING_POINT FOREIGN KEY(ID_MEETING_POINT) REFERENCES MEETING_POINT(ID_MEETING_POINT)
);


CREATE INDEX IDX_LOCALIZATION_MEETING ON LOCALIZATION (ID_MEETING);