-- SCRIPTS TABLE: MEETING_POINT

-- TABLE 'MEETING_POINT'
CREATE TABLE `MEETING_POINT` (
    ID_MEETING_POINT INTEGER NOT NULL AUTO_INCREMENT,
    ID_HOMELESS INTEGER NOT NULL,
	ID_MEETING_POINT_USER INTEGER,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_MEETING),
    CONSTRAINT FK_MEETING_POINT_MEETING_POINT_USER FOREIGN KEY(ID_MEETING_POINT) REFERENCES MEETING_POINT(ID_MEETING_POINT)
);

-- TABLE 'MEETING_POINT_USER'
CREATE TABLE `MEETING_POINT_USER` (
    ID_MEETING_POINT_USER INTEGER NOT NULL AUTO_INCREMENT,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_MEETING_CONTRIBUTOR)
);

