-- SCRIPTS TABLE: MEETING_POINT

-- TABLE 'MEETING_POINT'
CREATE TABLE `MEETING_POINT` (
    ID_MEETING_POINT INTEGER NOT NULL AUTO_INCREMENT,
    ID_HOMELESS INTEGER NOT NULL,
	ID_MEETING_POINT_USER INTEGER NOT NULL,
    ID_USER INTEGER NOT NULL,
	CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(ID_MEETING),
    CONSTRAINT FK_MEETING_POINT_HOMELESS FOREIGN KEY(ID_HOMELESS) REFERENCES HOMELESS(ID_HOMELESS),
    CONSTRAINT FK_MEETING_POINT_USER_USER FOREIGN KEY(ID_USER) REFERENCES `USER`(ID_USER)
);


