-- SCRIPTS TABLE: ORGANIZATION 

-- TABLE 'ORGANIZATION'
CREATE TABLE `ORGANIZATION` (
    ID_ORGANIZATION INTEGER NOT NULL AUTO_INCREMENT,
    `NAME` VARCHAR(100),
    DESC_ORGANIZATION VARCHAR(100),
    CNPJ VARCHAR(14),
    ID_USER INTEGER NOT NULL,
	PRIMARY KEY(ID_ORGANIZATION),
    CONSTRAINT FK_ORGANIZATION_USER FOREIGN KEY(ID_USER) REFERENCES `USER`(ID_USER)
);
